name: nba_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - shap
  - flask
  - joblib
  - nba_api
  - tqdm
